### ISSUE TITLE
can't install the module

### ISSUE THREAD

**Issue by cyprien-pixngraph** [donaldaverill/meteor-package-serialport#2]
Hello,
i want to test your module with my arduino, but i can't install it :
```
meteor add donaldaverill:serialport
 => Errors while adding packages:             
                                              
While checking for donaldaverill:serialport@1.4.10_2:
error: No compatible binary build found for this package. Contact the package author and ask them to publish it for
your platform.


```
I'm on a ubuntu 64 bits

**Comment by donaldaverill** [comment]
Hi, 
Thanks for the heads up. When I previously tried publishing with the newer version of serialport, I ran into this issue:
https://github.com/meteorhacks/npm/issues/76

I then accidentally dropped my arduino in a pint of beer and promptly abandoned the package update and marked the package on atmosphere as unmigrated(ie, broken). Anyway, I just now reverted to serialport 1.3.1 and republished and it seemed to work with publish-for-arch on OSX and Linux versions but not for Windows (got a similar shrinkwrap error).

I haven't had a chance to test it out, but give it a shot and let me know if it works for you or not. 

Since this package is just a simple wrapper for the npm module, another approach you can try is to use the meteorhacks:npm package to add serialport to your app :
https://atmospherejs.com/meteorhacks/npm

Also, looks like there's another serialport package available:
https://atmospherejs.com/spectrum/serialport

Cheers!

**Comment by cyprien-pixngraph** [comment]
Thanks for your answer. How is it possible to drop an arduino in a beer :) ? It was a small one ?
I've already tried with npm and it works just fine with version 1.4.6.
I will try with yours soon. 
Thanks for your work !

**Comment by donaldaverill** [comment]
It's an uno and as it turns out fits nice and snuggly in a standard pint glass. The arduino dried out and started working again a few days later. So, all is good there except for the stickiness.

I work in a brewpub and set the beer down on the ground to get it *away* from the electronics which were on a table I was sitting at, but the usb cable I was using at the time was about 10 feet long and super unwieldy. While tinkering other things attached to it, the uno fell off the table and dipped right into the beverage. Bullseye!

**Comment by Toebez** [comment]
I'm on the wishey now and can confirm that it is definitely moving back to 1.3.1 of serialport. Cost me all night to figure out this topic gave me the answer...
