### ISSUE TITLE
No compatible binary build found ?

### ISSUE THREAD

**Issue by clairezed** [donaldaverill/meteor-package-serialport#3]
Hello ! 
I'm doing this week end kind of a hackaton, and I'd like to use Meteor with Arduino. While trying to install your package, I add the following message :
 "While checking for donaldaverill:serialport@1.4.10_2: error: No compatible binary build found for this package. Contact the package author and ask them to publish it for your platform."

Therefore, I'm transmitting you !

**Comment by donaldaverill** [comment]
Hi Claire,

The reason 1.4.10 can't load is that there seems to be an [issue](https://github.com/donaldaverill/meteor-package-serialport/issues/2) (not sure what the issue is exactly) with [serialport](https://www.npmjs.com/package/serialport) versions above 1.3.1 and meteor. As it turns out, I updated the package and published version 1.4.10 without testing first. As far as I can tell, the lastest serialport version I can get working with meteor is 1.3.1.

I've republished the package with the npm serialport version 1.3.1 as version 3.1.1 with meteor. At the moment, there are no build machines available for os x. When one becomes available I'll publish this package for os x. When I try to publish to windows, I get errors, so I may not get that working. The linux versions seemed to have worked, but I don't have a linux machine handy to test. 

A couple things to try instead:
- Probably not recommended (although I just downloaded it and it works for me), but you can try the old example I made: https://github.com/donaldaverill/meteor-app-example-arduino-serialport
- Use https://github.com/meteorhacks/npm and include serialport 1.3.1, or whatever version you can get working (recommended)

- Download this package and put it in the packages folder in your app. Then set the version in package.js to 1.3.1 like so:
```js
Npm.depends({
  'serialport': '1.3.1'
});
```
And then add the package like:
```
meteor add donaldaverill:serialport
```

**Comment by donaldaverill** [comment]
version 3.1.1 should be published for os x now. Still no luck with windows however.

**Comment by clairezed** [comment]
Hi Donald, I had no time to give you news from your modification. I'm on linux and it worked perfectly with a simple 'meteor add' ! So thank you so much for your reactivity.

**Comment by llwoll** [comment]
Hello:
    Sorry for my poor english   ......
    I am working well on win10,but there is one trouble when i transform to os x !
 
    While checking for fourquet:serialport@2.0.2_1:
   error: No compatible binary build found for this package. Contact the package author and ask them to    publish it for  your platform.

**Comment by donaldaverill** [comment]
Hi,

When I first tried publishing the package the os x build machine was not available and I must have given up before I could find one. Just now, I managed to get a build machine and published for os x. Try again and let me know if it works for you.

**Comment by llwoll** [comment]
Thanks ! every thing is all right now
